### ISSUE TITLE
Dependencies cannot succeed

### ISSUE THREAD

**Issue by sotex** [fireworq/fireworq#27] opened 2019-06-17 02:33 UTC
### Situation 1
```bash
[INFO]  --> Fetching google.golang.org/appengine.
[WARN]  Unable to checkout google.golang.org/appengine
[ERROR] Update failed for google.golang.org/appengine: Cannot detect VCS
[ERROR] Failed to install: Cannot detect VCS
```
I'll be successful after changing `google.golang.org/appengine` in the file glide.lock to `github.com/golang/appengine`

### Situation 2
```bash
cd vendor/github.com/golang/mock/mockgen && go build
mockgen.go:38:2: cannot find package "github.com/golang/mock/mockgen/model" in any of:
        /usr/lib/golang/src/github.com/golang/mock/mockgen/model (from $GOROOT)
        /home/hdfs/test/gosrc/src/github.com/golang/mock/mockgen/model (from $GOPATH)
```
Can continue after executing the `go get github.com/golang/mock/mockgen/model` command, but will continue to encounter errors
```bash
[INFO]  --> Exporting github.com/lestrrat/go-server-starter
[INFO]  Replacing existing vendor dependencies
GOOS= GOARCH= go get github.com/jessevdk/go-assets-builder
touch AUTHORS
touch CREDITS
cd vendor/github.com/golang/mock/mockgen && go build
PATH=/home/hdfs/test/gosrc/fireworq/vendor/github.com/golang/mock/mockgen:/usr/local/bin:/usr/bin:/home/hdfs/bin:/usr/local/sbin:/usr/sbin:/home/hdfs/hadoop-3.1.2/bin:/home/hdfs/hadoop-3.1.2/sbin GOOS= GOARCH= go generate -x ./...
go-assets-builder -p main -o assets.go LICENSE AUTHORS CREDITS
main.go:1: running "go-assets-builder": exec: "go-assets-builder": executable file not found in $PATH
go-assets-builder -p mysql -o assets.go ../../data/jobqueue/mysql
jobqueue/mysql/sql.go:1: running "go-assets-builder": exec: "go-assets-builder": executable file not found in $PATH
go-assets-builder -p mysql -o assets.go ../../data/repository
repository/mysql/db.go:1: running "go-assets-builder": exec: "go-assets-builder": executable file not found in $PATH
mockgen -source application.go -destination mock_web_test.go -package web
mockgen -source ../repository/repository.go -destination mock_web_repository_test.go -package web
mockgen -source ../jobqueue/jobqueue.go -destination mock_jobqueue_test.go -package web -self_package github.com/fireworq/fireworq/web
mockgen -source ../jobqueue/inspector.go -destination mock_inspector_test.go -package web -self_package github.com/fireworq/fireworq/web
```

**Comment by tarao** [comment] 2019-06-17 03:51
> `google.golang.org/appengine`

We didn't need it at all since we are not doing `+build appengine`.
I removed it in #28.

> `cd vendor/github.com/golang/mock/mockgen && go build`

Hmm, I couldn't reproduce this.

What Go version are you using?
Or does it work if you try again after `make clean` and `rm -rf vendor/`?

I guess you are compiling Fireworq on your native environment but our recommended way is to build it in a Docker container.  The following command will build Fireworq for your `$os` and `$arch`.
(Note that we only support `os=linux arch=amd64` or `os=darwin arch=amd64` for now.)

```
GOOS="$os" GOARCH="$arch" script/docker/build
```

**Comment by tarao** [comment] 2019-11-22 03:06
@sotex I close this for now because there is nothing I can do.  Please reopen with providing more information if there is still a problem.

**Closed by tarao** 2019-11-22 03:06 UTC
